# Generated by Django 3.0 on 2020-01-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255, null=True)),
                ('rated', models.CharField(max_length=10, null=True)),
                ('released', models.CharField(max_length=255, null=True)),
                ('runtime', models.CharField(max_length=255, null=True)),
                ('genre', models.CharField(max_length=255, null=True)),
                ('director', models.TextField(null=True)),
                ('writer', models.TextField(null=True)),
                ('actors', models.TextField(null=True)),
                ('plot', models.TextField(null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('awards', models.TextField(null=True)),
                ('poster', models.TextField(null=True)),
                ('metascore', models.CharField(max_length=255, null=True)),
                ('imdbrating', models.CharField(max_length=255, null=True)),
                ('imdbvotes', models.CharField(max_length=255, null=True)),
                ('imdbid', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('dvd', models.CharField(max_length=255, null=True)),
                ('boxoffice', models.CharField(max_length=255, null=True)),
                ('production', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
            ],
        ),
    ]
