# Generated by Django 3.0 on 2020-01-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omdbapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbid',
            new_name='imdb_id',
        ),
    ]
