# Generated by Django 3.0 on 2020-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdbapi', '0002_auto_20200113_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('series', 'series'), ('episode', 'episode')], max_length=255),
        ),
    ]
