# Generated by Django 3.0 on 2020-01-16 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omdbapi', '0005_movierating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermovielist',
            name='name',
            field=models.CharField(choices=[('Favourites', 'Favourites'), ('Want to see', 'Want to see')], max_length=128),
        ),
    ]
