# Generated by Django 3.0 on 2020-01-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omdbapi', '0009_auto_20200116_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omdbapi.Movie'),
        ),
    ]
